### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ruttydm** [pokerregion/poker#33]
I just installed the package and I imported it in a simple python3 script.
But i get the following error:

Traceback (most recent call last):
  File "hand_insertor.py", line 3, in <module>
    import poker
  File "/usr/local/lib/python3.5/dist-packages/poker/__init__.py", line 10, in <module>
    from poker.card import Suit, Rank, Card, FACE_RANKS, BROADWAY_RANKS
  File "/usr/local/lib/python3.5/dist-packages/poker/card.py", line 51, in <module>
    FACE_RANKS = Rank('J'), Rank('Q'), Rank('K')
  File "/usr/lib/python3.5/enum.py", line 241, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.5/enum.py", line 476, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'J' is not a valid Rank

I also tried to run it with python2 but then I get the error:

ImportError: No module named poker

**Comment by ruttydm** [comment]
Why closing this issue when it is not solved?
