### ISSUE TITLE
ValueError: 'J' is not a valid Rank

### ISSUE THREAD

**Issue by MikeB242** [pokerregion/poker#34]
Hi,

After installing on Anaconda using:

pip install poker

I receive:

Successfully built poker parsedatetime pathlib configparser future
Installing collected packages: future, parsedatetime, cached-property, enum34, pathlib, configparser, poker
Successfully installed cached-property-1.3.0 configparser-3.5.0 enum34-1.1.6 future-0.16.0 parsedatetime-2.4 pathlib-1.0.1 poker-0.22.2

Then when I try:

from poker import Suit

I get the error:

ValueError: 'J' is not a valid Rank

Is there a fix to this or have I done something incorrect?

Regards,

Mike

**Comment by kissgyorgy** [comment]
What is the output of `pip -V`?

**Comment by MikeB242** [comment]
Hi György,


Thanks for getting ba



runfile('C:/Users/Mike\'s/.spyder-py3/temp.py', wdir='C:/Users/Mike\'s/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-2-ded10d9e9c58>", line 1, in <module>
    runfile('C:/Users/Mike\'s/.spyder-py3/temp.py', wdir='C:/Users/Mike\'s/.spyder-py3')

  File "C:\My_Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\My_Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Mike's/.spyder-py3/temp.py", line 8, in <module>
    from deuces import Card

  File "C:\My_Anaconda\lib\site-packages\deuces\__init__.py", line 1, in <module>
    from card import Card

ModuleNotFoundError: No module named 'card'


________________________________
