### ISSUE TITLE
import issue - 'J' is not a valid rank

### ISSUE THREAD

**Issue by SeanIsaGit** [pokerregion/poker#35]
I have only just installed 'poker' and on the very first attempt at importing i got 'J' is not a valid rank. I can't see why. My output is...

>>> import poker
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import poker
  File "C:\Users\Sean\AppData\Local\Programs\Python\Python36-32\lib\site-packages\poker\__init__.py", line 10, in <module>
    from poker.card import Suit, Rank, Card, FACE_RANKS, BROADWAY_RANKS
  File "C:\Users\Sean\AppData\Local\Programs\Python\Python36-32\lib\site-packages\poker\card.py", line 51, in <module>
    FACE_RANKS = Rank('J'), Rank('Q'), Rank('K')
  File "C:\Users\Sean\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\Sean\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 533, in __new__
    return cls._missing_(value)
  File "C:\Users\Sean\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'J' is not a valid Rank

**Comment by mathijs-creemers-uh** [comment]
I get the same issue after doing a pip install using python 3.5
